"""Explanation half: plain-English explanations for ambiguous
breaks, generated by Claude from structured facts pulled directly from
this project's own CSVs -- never invented. Two genuinely ambiguous cases
this project actually has, not synthetic breaks a rule already resolves
cleanly:

  1. Fuzzy-match candidates with more than one plausible real trade
     (reconciliation/fuzzy_match_{clearing,confirm}.csv) -- exactly the
     kind of judgment call README flagged as needing a human (or
     a tighter tolerance) to adjudicate.
  2. The "TIMING but on_time" edge cases -- a record that was
     genuinely late relative to normal processing but still lands inside
     the looser T+1 settlement window (root_cause/README.md's
     "Classification" section).

Disclosed explicitly, every time: this is an assistive explanation, not
an authoritative verdict. The prompt instructs the model to use ONLY the
facts it's given and to say so plainly if something can't be determined
from them -- it is never asked to guess at a resolution.
"""

from __future__ import annotations

import csv
import json
import os
import pathlib

import anthropic
from dotenv import load_dotenv

load_dotenv()

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_REAL = REPO_ROOT / "data" / "real"
DATA_SYNTHETIC = REPO_ROOT / "data" / "synthetic"
RECONCILIATION_DIR = REPO_ROOT / "reconciliation"
ROOT_CAUSE_DIR = REPO_ROOT / "root_cause"
LIFECYCLE_DIR = REPO_ROOT / "lifecycle"

MODEL = "claude-haiku-4-5-20251001"  # bulk, templated synthesis over provided facts -- cheap model is sufficient

SYSTEM_PROMPT = """You are an assistive explanation tool for a post-trade reconciliation \
system. You will be given structured facts about ONE trade break, drawn directly from the \
system's own database. Write a 2-4 sentence plain-English explanation for a human operations \
analyst.

Rules:
- Use ONLY the facts provided. Never invent a value, a cause, or a resolution not present \
in the data.
- If the facts don't determine a clear cause or resolution, say so explicitly -- do not \
guess or imply more confidence than the data supports.
- End every explanation with exactly this sentence, verbatim: "This is an AI-generated \
explanation for triage only; verify against the source records before acting on it."
"""


def _read_csv(path: pathlib.Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def _lookup(rows: list[dict], key_fields: dict) -> dict | None:
    for row in rows:
        if all(row.get(k) == v for k, v in key_fields.items()):
            return row
    return None


def gather_fuzzy_match_context(orphan_ref: str, stage: str) -> dict:
    fname = "fuzzy_match_clearing.csv" if stage == "clearing" else "fuzzy_match_confirm.csv"
    fuzzy_rows = _read_csv(RECONCILIATION_DIR / fname)
    match = _lookup(fuzzy_rows, {"orphan_ref": orphan_ref})
    if match is None:
        raise ValueError(f"no fuzzy-match row found for {orphan_ref} at stage {stage}")

    synth_file = "clearing_statements.csv" if stage == "clearing" else "exchange_confirms.csv"
    ref_col = "clearing_ref" if stage == "clearing" else "confirm_ref"
    synthetic_rows = _read_csv(DATA_SYNTHETIC / synth_file)
    orphan_record = _lookup(synthetic_rows, {ref_col: orphan_ref})

    candidate_refs = [r for r in match["candidate_trade_refs"].split(";") if r]
    trades = {f"{r['venue']}:{r['native_trade_id']}": r for r in _read_csv(DATA_REAL / "trades_real.csv")}
    candidates = [trades[ref] for ref in candidate_refs if ref in trades]

    return {
        "case_type": "orphan_record_with_fuzzy_candidates",
        "stage": stage,
        "orphan_record": orphan_record,
        "candidate_count": len(candidates),
        "candidate_trades": candidates,
        "fuzzy_match_tolerance": "same venue+symbol, within 1 hour, price/quantity within 5% "
        "(reconciliation/matching_engine.py FUZZY_TIME_WINDOW/FUZZY_TOLERANCE_PCT)",
    }


def gather_timing_edge_case_context(trade_id_ref: str, stage: str) -> dict:
    reconciliation_rows = _read_csv(RECONCILIATION_DIR / "reconciliation_results.csv")
    label_rows = _read_csv(ROOT_CAUSE_DIR / "root_cause_labels.csv")
    lifecycle_rows = _read_csv(LIFECYCLE_DIR / "lifecycle_events.csv")
    trades = {f"{r['venue']}:{r['native_trade_id']}": r for r in _read_csv(DATA_REAL / "trades_real.csv")}

    stage_to_lifecycle = {"confirm": "confirmed", "clearing": "settled"}
    reconciliation = _lookup(reconciliation_rows, {"trade_id_ref": trade_id_ref, "stage": stage})
    label = _lookup(label_rows, {"trade_id_ref": trade_id_ref, "stage": stage})
    lifecycle_event = _lookup(lifecycle_rows, {"trade_id_ref": trade_id_ref, "stage_code": stage_to_lifecycle[stage]})

    synth_file = "clearing_statements.csv" if stage == "clearing" else "exchange_confirms.csv"
    synthetic_rows = _read_csv(DATA_SYNTHETIC / synth_file)
    synthetic_record = _lookup(synthetic_rows, {"trade_id_ref": trade_id_ref})

    return {
        "case_type": "timing_breach_within_settlement_sla",
        "stage": stage,
        "real_trade": trades.get(trade_id_ref),
        "synthetic_record": synthetic_record,
        "reconciliation_result": reconciliation,
        "root_cause_label": label,
        "lifecycle_event": lifecycle_event,
    }


def _extract_text(response: anthropic.types.Message) -> str:
    """Some models prepend a ThinkingBlock before the TextBlock --
    content[0] isn't reliably the answer."""
    for block in response.content:
        if block.type == "text":
            return block.text.strip()
    raise ValueError("no text block in response")


def explain(context: dict) -> str:
    client = anthropic.Anthropic()
    response = client.messages.create(
        model=MODEL,
        max_tokens=300,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": json.dumps(context, default=str, indent=2)}],
    )
    return _extract_text(response)


def main() -> None:
    import sys

    if len(sys.argv) < 4:
        print("usage: break_explainer.py <fuzzy|timing> <trade_id_ref_or_orphan_ref> <stage>")
        raise SystemExit(1)

    case_type, ref, stage = sys.argv[1], sys.argv[2], sys.argv[3]
    context = gather_fuzzy_match_context(ref, stage) if case_type == "fuzzy" else gather_timing_edge_case_context(ref, stage)

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("ANTHROPIC_API_KEY not set -- context gathered but no explanation generated.")
        print(json.dumps(context, default=str, indent=2))
        raise SystemExit(0)

    explanation = explain(context)
    print(explanation)


if __name__ == "__main__":
    main()
